POST http://localhost:4000/api/auth/register HTTP/1.1
content-type: application/json

{
    "username": "Test User 5",
    "email": "test5@test.com",
    "password": "admin1234",
    "isAdmin": false
}

###

POST http://localhost:4000/api/auth/login HTTP/1.1
content-type: application/json

{
    "email": "test3@test.com"
}